// Code generated by protoc-gen-go-log-valuer. DO NOT EDIT.
//
// source: test/example.proto

package test

import (
	slog "log/slog"
)

func (x *ExampleMessage) LogValue() slog.Value {
	if x == nil {
		return slog.AnyValue(nil)
	}
	attrs := make([]slog.Attr, 0, 3)
	attrs = append(attrs, slog.String("message", x.Message))
	attrs = append(attrs, slog.Int64("count", int64(x.Count)))
	attrs = append(attrs, slog.String("secret", "[REDACTED]"))
	return slog.GroupValue(attrs...)
}
