// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: test/example.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExampleMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Secret        string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleMessage) Reset() {
	*x = ExampleMessage{}
	mi := &file_test_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleMessage) ProtoMessage() {}

func (x *ExampleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleMessage.ProtoReflect.Descriptor instead.
func (*ExampleMessage) Descriptor() ([]byte, []int) {
	return file_test_example_proto_rawDescGZIP(), []int{0}
}

func (x *ExampleMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExampleMessage) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ExampleMessage) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_test_example_proto protoreflect.FileDescriptor

const file_test_example_proto_rawDesc = "" +
	"\n" +
	"\x12test/example.proto\x12\x06simple\"]\n" +
	"\x0eExampleMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1b\n" +
	"\x06secret\x18\x03 \x01(\tB\x03\x80\x01\x01R\x06secretB2Z0github.com/kei2100/protoc-gen-go-log-valuer/testb\x06proto3"

var (
	file_test_example_proto_rawDescOnce sync.Once
	file_test_example_proto_rawDescData []byte
)

func file_test_example_proto_rawDescGZIP() []byte {
	file_test_example_proto_rawDescOnce.Do(func() {
		file_test_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_example_proto_rawDesc), len(file_test_example_proto_rawDesc)))
	})
	return file_test_example_proto_rawDescData
}

var file_test_example_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_example_proto_goTypes = []any{
	(*ExampleMessage)(nil), // 0: simple.ExampleMessage
}
var file_test_example_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_example_proto_init() }
func file_test_example_proto_init() {
	if File_test_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_example_proto_rawDesc), len(file_test_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_example_proto_goTypes,
		DependencyIndexes: file_test_example_proto_depIdxs,
		MessageInfos:      file_test_example_proto_msgTypes,
	}.Build()
	File_test_example_proto = out.File
	file_test_example_proto_goTypes = nil
	file_test_example_proto_depIdxs = nil
}
