// Code generated by protoc-gen-go-log-valuer. DO NOT EDIT.
//
// source: test/list_type.proto

package test

import (
	fmt "fmt"
	slog "log/slog"
)

func (x *ListType) LogValue() slog.Value {
	if x == nil {
		return slog.AnyValue(nil)
	}
	attrs := make([]slog.Attr, 0, 1)
	if len(x.StringList) != 0 {
		attrs0 := make([]slog.Attr, 0, len(x.StringList))
		for i, v := range x.StringList {
			attrs0 = append(attrs0, slog.String(fmt.Sprintf("%d", i), v))
		}
		attrs = append(attrs, slog.Any("string_list", attrs0))
	}
	return slog.GroupValue(attrs...)
}
