// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: test/map_type.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapType struct {
	state           protoimpl.MessageState         `protogen:"open.v1"`
	StringMap       map[string]string              `protobuf:"bytes,1,rep,name=string_map,json=stringMap,proto3" json:"string_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FloatMap        map[string]float32             `protobuf:"bytes,2,rep,name=float_map,json=floatMap,proto3" json:"float_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	IntKeyMap       map[int32]string               `protobuf:"bytes,3,rep,name=int_key_map,json=intKeyMap,proto3" json:"int_key_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MessageMap      map[string]*MapType_MapMessage `protobuf:"bytes,4,rep,name=message_map,json=messageMap,proto3" json:"message_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StructMap       map[string]*structpb.Struct    `protobuf:"bytes,5,rep,name=struct_map,json=structMap,proto3" json:"struct_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EmptyStringMap  map[string]string              `protobuf:"bytes,6,rep,name=empty_string_map,json=emptyStringMap,proto3" json:"empty_string_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EmptyMessageMap map[string]*MapType_MapMessage `protobuf:"bytes,7,rep,name=empty_message_map,json=emptyMessageMap,proto3" json:"empty_message_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NullStringMap   map[string]string              `protobuf:"bytes,8,rep,name=null_string_map,json=nullStringMap,proto3" json:"null_string_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NullMessageMap  map[string]*MapType_MapMessage `protobuf:"bytes,9,rep,name=null_message_map,json=nullMessageMap,proto3" json:"null_message_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MapType) Reset() {
	*x = MapType{}
	mi := &file_test_map_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapType) ProtoMessage() {}

func (x *MapType) ProtoReflect() protoreflect.Message {
	mi := &file_test_map_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapType.ProtoReflect.Descriptor instead.
func (*MapType) Descriptor() ([]byte, []int) {
	return file_test_map_type_proto_rawDescGZIP(), []int{0}
}

func (x *MapType) GetStringMap() map[string]string {
	if x != nil {
		return x.StringMap
	}
	return nil
}

func (x *MapType) GetFloatMap() map[string]float32 {
	if x != nil {
		return x.FloatMap
	}
	return nil
}

func (x *MapType) GetIntKeyMap() map[int32]string {
	if x != nil {
		return x.IntKeyMap
	}
	return nil
}

func (x *MapType) GetMessageMap() map[string]*MapType_MapMessage {
	if x != nil {
		return x.MessageMap
	}
	return nil
}

func (x *MapType) GetStructMap() map[string]*structpb.Struct {
	if x != nil {
		return x.StructMap
	}
	return nil
}

func (x *MapType) GetEmptyStringMap() map[string]string {
	if x != nil {
		return x.EmptyStringMap
	}
	return nil
}

func (x *MapType) GetEmptyMessageMap() map[string]*MapType_MapMessage {
	if x != nil {
		return x.EmptyMessageMap
	}
	return nil
}

func (x *MapType) GetNullStringMap() map[string]string {
	if x != nil {
		return x.NullStringMap
	}
	return nil
}

func (x *MapType) GetNullMessageMap() map[string]*MapType_MapMessage {
	if x != nil {
		return x.NullMessageMap
	}
	return nil
}

type MapType_MapMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretVal     string                 `protobuf:"bytes,1,opt,name=secret_val,json=secretVal,proto3" json:"secret_val,omitempty"`
	DoubleVal     float64                `protobuf:"fixed64,2,opt,name=double_val,json=doubleVal,proto3" json:"double_val,omitempty"`
	FloatVal      float32                `protobuf:"fixed32,3,opt,name=float_val,json=floatVal,proto3" json:"float_val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapType_MapMessage) Reset() {
	*x = MapType_MapMessage{}
	mi := &file_test_map_type_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapType_MapMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapType_MapMessage) ProtoMessage() {}

func (x *MapType_MapMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_map_type_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapType_MapMessage.ProtoReflect.Descriptor instead.
func (*MapType_MapMessage) Descriptor() ([]byte, []int) {
	return file_test_map_type_proto_rawDescGZIP(), []int{0, 9}
}

func (x *MapType_MapMessage) GetSecretVal() string {
	if x != nil {
		return x.SecretVal
	}
	return ""
}

func (x *MapType_MapMessage) GetDoubleVal() float64 {
	if x != nil {
		return x.DoubleVal
	}
	return 0
}

func (x *MapType_MapMessage) GetFloatVal() float32 {
	if x != nil {
		return x.FloatVal
	}
	return 0
}

var File_test_map_type_proto protoreflect.FileDescriptor

const file_test_map_type_proto_rawDesc = "" +
	"\n" +
	"\x13test/map_type.proto\x12\x06simple\x1a\x1cgoogle/protobuf/struct.proto\"\x9e\v\n" +
	"\aMapType\x12=\n" +
	"\n" +
	"string_map\x18\x01 \x03(\v2\x1e.simple.MapType.StringMapEntryR\tstringMap\x12:\n" +
	"\tfloat_map\x18\x02 \x03(\v2\x1d.simple.MapType.FloatMapEntryR\bfloatMap\x12>\n" +
	"\vint_key_map\x18\x03 \x03(\v2\x1e.simple.MapType.IntKeyMapEntryR\tintKeyMap\x12@\n" +
	"\vmessage_map\x18\x04 \x03(\v2\x1f.simple.MapType.MessageMapEntryR\n" +
	"messageMap\x12=\n" +
	"\n" +
	"struct_map\x18\x05 \x03(\v2\x1e.simple.MapType.StructMapEntryR\tstructMap\x12M\n" +
	"\x10empty_string_map\x18\x06 \x03(\v2#.simple.MapType.EmptyStringMapEntryR\x0eemptyStringMap\x12P\n" +
	"\x11empty_message_map\x18\a \x03(\v2$.simple.MapType.EmptyMessageMapEntryR\x0femptyMessageMap\x12J\n" +
	"\x0fnull_string_map\x18\b \x03(\v2\".simple.MapType.NullStringMapEntryR\rnullStringMap\x12M\n" +
	"\x10null_message_map\x18\t \x03(\v2#.simple.MapType.NullMessageMapEntryR\x0enullMessageMap\x1a<\n" +
	"\x0eStringMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rFloatMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1a<\n" +
	"\x0eIntKeyMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aY\n" +
	"\x0fMessageMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.simple.MapType.MapMessageR\x05value:\x028\x01\x1aU\n" +
	"\x0eStructMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value:\x028\x01\x1aA\n" +
	"\x13EmptyStringMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a^\n" +
	"\x14EmptyMessageMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.simple.MapType.MapMessageR\x05value:\x028\x01\x1a@\n" +
	"\x12NullStringMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a]\n" +
	"\x13NullMessageMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.simple.MapType.MapMessageR\x05value:\x028\x01\x1al\n" +
	"\n" +
	"MapMessage\x12\"\n" +
	"\n" +
	"secret_val\x18\x01 \x01(\tB\x03\x80\x01\x01R\tsecretVal\x12\x1d\n" +
	"\n" +
	"double_val\x18\x02 \x01(\x01R\tdoubleVal\x12\x1b\n" +
	"\tfloat_val\x18\x03 \x01(\x02R\bfloatValB2Z0github.com/kei2100/protoc-gen-go-log-valuer/testb\x06proto3"

var (
	file_test_map_type_proto_rawDescOnce sync.Once
	file_test_map_type_proto_rawDescData []byte
)

func file_test_map_type_proto_rawDescGZIP() []byte {
	file_test_map_type_proto_rawDescOnce.Do(func() {
		file_test_map_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_map_type_proto_rawDesc), len(file_test_map_type_proto_rawDesc)))
	})
	return file_test_map_type_proto_rawDescData
}

var file_test_map_type_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_test_map_type_proto_goTypes = []any{
	(*MapType)(nil),            // 0: simple.MapType
	nil,                        // 1: simple.MapType.StringMapEntry
	nil,                        // 2: simple.MapType.FloatMapEntry
	nil,                        // 3: simple.MapType.IntKeyMapEntry
	nil,                        // 4: simple.MapType.MessageMapEntry
	nil,                        // 5: simple.MapType.StructMapEntry
	nil,                        // 6: simple.MapType.EmptyStringMapEntry
	nil,                        // 7: simple.MapType.EmptyMessageMapEntry
	nil,                        // 8: simple.MapType.NullStringMapEntry
	nil,                        // 9: simple.MapType.NullMessageMapEntry
	(*MapType_MapMessage)(nil), // 10: simple.MapType.MapMessage
	(*structpb.Struct)(nil),    // 11: google.protobuf.Struct
}
var file_test_map_type_proto_depIdxs = []int32{
	1,  // 0: simple.MapType.string_map:type_name -> simple.MapType.StringMapEntry
	2,  // 1: simple.MapType.float_map:type_name -> simple.MapType.FloatMapEntry
	3,  // 2: simple.MapType.int_key_map:type_name -> simple.MapType.IntKeyMapEntry
	4,  // 3: simple.MapType.message_map:type_name -> simple.MapType.MessageMapEntry
	5,  // 4: simple.MapType.struct_map:type_name -> simple.MapType.StructMapEntry
	6,  // 5: simple.MapType.empty_string_map:type_name -> simple.MapType.EmptyStringMapEntry
	7,  // 6: simple.MapType.empty_message_map:type_name -> simple.MapType.EmptyMessageMapEntry
	8,  // 7: simple.MapType.null_string_map:type_name -> simple.MapType.NullStringMapEntry
	9,  // 8: simple.MapType.null_message_map:type_name -> simple.MapType.NullMessageMapEntry
	10, // 9: simple.MapType.MessageMapEntry.value:type_name -> simple.MapType.MapMessage
	11, // 10: simple.MapType.StructMapEntry.value:type_name -> google.protobuf.Struct
	10, // 11: simple.MapType.EmptyMessageMapEntry.value:type_name -> simple.MapType.MapMessage
	10, // 12: simple.MapType.NullMessageMapEntry.value:type_name -> simple.MapType.MapMessage
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_test_map_type_proto_init() }
func file_test_map_type_proto_init() {
	if File_test_map_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_map_type_proto_rawDesc), len(file_test_map_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_map_type_proto_goTypes,
		DependencyIndexes: file_test_map_type_proto_depIdxs,
		MessageInfos:      file_test_map_type_proto_msgTypes,
	}.Build()
	File_test_map_type_proto = out.File
	file_test_map_type_proto_goTypes = nil
	file_test_map_type_proto_depIdxs = nil
}
