// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: test/scalar_type.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enumerations
// https://developers.google.com/protocol-buffers/docs/proto#enum
type ScalarType_Enum int32

const (
	ScalarType_ENUM_0 ScalarType_Enum = 0
	ScalarType_ENUM_1 ScalarType_Enum = 1
	ScalarType_ENUM_2 ScalarType_Enum = 2
)

// Enum value maps for ScalarType_Enum.
var (
	ScalarType_Enum_name = map[int32]string{
		0: "ENUM_0",
		1: "ENUM_1",
		2: "ENUM_2",
	}
	ScalarType_Enum_value = map[string]int32{
		"ENUM_0": 0,
		"ENUM_1": 1,
		"ENUM_2": 2,
	}
)

func (x ScalarType_Enum) Enum() *ScalarType_Enum {
	p := new(ScalarType_Enum)
	*p = x
	return p
}

func (x ScalarType_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScalarType_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_test_scalar_type_proto_enumTypes[0].Descriptor()
}

func (ScalarType_Enum) Type() protoreflect.EnumType {
	return &file_test_scalar_type_proto_enumTypes[0]
}

func (x ScalarType_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScalarType_Enum.Descriptor instead.
func (ScalarType_Enum) EnumDescriptor() ([]byte, []int) {
	return file_test_scalar_type_proto_rawDescGZIP(), []int{0, 0}
}

type ScalarType struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SecretVal string                 `protobuf:"bytes,1,opt,name=secret_val,json=secretVal,proto3" json:"secret_val,omitempty"`
	// Scalar Value Types
	// https://developers.google.com/protocol-buffers/docs/proto#scalar
	DoubleVal   float64         `protobuf:"fixed64,2,opt,name=double_val,json=doubleVal,proto3" json:"double_val,omitempty"`
	FloatVal    float32         `protobuf:"fixed32,3,opt,name=float_val,json=floatVal,proto3" json:"float_val,omitempty"`
	Int32Val    int32           `protobuf:"varint,4,opt,name=int32_val,json=int32Val,proto3" json:"int32_val,omitempty"`
	Int64Val    int64           `protobuf:"varint,5,opt,name=int64_val,json=int64Val,proto3" json:"int64_val,omitempty"`
	Uint32Val   uint32          `protobuf:"varint,6,opt,name=uint32_val,json=uint32Val,proto3" json:"uint32_val,omitempty"`
	Uint64Val   uint64          `protobuf:"varint,7,opt,name=uint64_val,json=uint64Val,proto3" json:"uint64_val,omitempty"`
	Sint32Val   int32           `protobuf:"zigzag32,8,opt,name=sint32_val,json=sint32Val,proto3" json:"sint32_val,omitempty"`
	Sint64Val   int64           `protobuf:"zigzag64,9,opt,name=sint64_val,json=sint64Val,proto3" json:"sint64_val,omitempty"`
	Fixed32Val  uint32          `protobuf:"fixed32,10,opt,name=fixed32_val,json=fixed32Val,proto3" json:"fixed32_val,omitempty"`
	Fixed64Val  uint64          `protobuf:"fixed64,11,opt,name=fixed64_val,json=fixed64Val,proto3" json:"fixed64_val,omitempty"`
	Sfixed32Val int32           `protobuf:"fixed32,12,opt,name=sfixed32_val,json=sfixed32Val,proto3" json:"sfixed32_val,omitempty"`
	Sfixed64Val int64           `protobuf:"fixed64,13,opt,name=sfixed64_val,json=sfixed64Val,proto3" json:"sfixed64_val,omitempty"`
	BoolVal     bool            `protobuf:"varint,14,opt,name=bool_val,json=boolVal,proto3" json:"bool_val,omitempty"`
	StringVal   string          `protobuf:"bytes,15,opt,name=string_val,json=stringVal,proto3" json:"string_val,omitempty"`
	BytesVal    []byte          `protobuf:"bytes,16,opt,name=bytes_val,json=bytesVal,proto3" json:"bytes_val,omitempty"`
	EnumVal     ScalarType_Enum `protobuf:"varint,17,opt,name=enum_val,json=enumVal,proto3,enum=simple.ScalarType_Enum" json:"enum_val,omitempty"`
	// Oneof
	// https://developers.google.com/protocol-buffers/docs/proto#oneof
	//
	// Types that are valid to be assigned to OneofVal:
	//
	//	*ScalarType_OneofStringVal
	//	*ScalarType_OneofInt64Val
	//	*ScalarType_OneofBoolVal
	OneofVal isScalarType_OneofVal `protobuf_oneof:"oneof_val"`
	// Camelcasing
	XString       string `protobuf:"bytes,21,opt,name=_String,json=String,proto3" json:"_String,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalarType) Reset() {
	*x = ScalarType{}
	mi := &file_test_scalar_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalarType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarType) ProtoMessage() {}

func (x *ScalarType) ProtoReflect() protoreflect.Message {
	mi := &file_test_scalar_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarType.ProtoReflect.Descriptor instead.
func (*ScalarType) Descriptor() ([]byte, []int) {
	return file_test_scalar_type_proto_rawDescGZIP(), []int{0}
}

func (x *ScalarType) GetSecretVal() string {
	if x != nil {
		return x.SecretVal
	}
	return ""
}

func (x *ScalarType) GetDoubleVal() float64 {
	if x != nil {
		return x.DoubleVal
	}
	return 0
}

func (x *ScalarType) GetFloatVal() float32 {
	if x != nil {
		return x.FloatVal
	}
	return 0
}

func (x *ScalarType) GetInt32Val() int32 {
	if x != nil {
		return x.Int32Val
	}
	return 0
}

func (x *ScalarType) GetInt64Val() int64 {
	if x != nil {
		return x.Int64Val
	}
	return 0
}

func (x *ScalarType) GetUint32Val() uint32 {
	if x != nil {
		return x.Uint32Val
	}
	return 0
}

func (x *ScalarType) GetUint64Val() uint64 {
	if x != nil {
		return x.Uint64Val
	}
	return 0
}

func (x *ScalarType) GetSint32Val() int32 {
	if x != nil {
		return x.Sint32Val
	}
	return 0
}

func (x *ScalarType) GetSint64Val() int64 {
	if x != nil {
		return x.Sint64Val
	}
	return 0
}

func (x *ScalarType) GetFixed32Val() uint32 {
	if x != nil {
		return x.Fixed32Val
	}
	return 0
}

func (x *ScalarType) GetFixed64Val() uint64 {
	if x != nil {
		return x.Fixed64Val
	}
	return 0
}

func (x *ScalarType) GetSfixed32Val() int32 {
	if x != nil {
		return x.Sfixed32Val
	}
	return 0
}

func (x *ScalarType) GetSfixed64Val() int64 {
	if x != nil {
		return x.Sfixed64Val
	}
	return 0
}

func (x *ScalarType) GetBoolVal() bool {
	if x != nil {
		return x.BoolVal
	}
	return false
}

func (x *ScalarType) GetStringVal() string {
	if x != nil {
		return x.StringVal
	}
	return ""
}

func (x *ScalarType) GetBytesVal() []byte {
	if x != nil {
		return x.BytesVal
	}
	return nil
}

func (x *ScalarType) GetEnumVal() ScalarType_Enum {
	if x != nil {
		return x.EnumVal
	}
	return ScalarType_ENUM_0
}

func (x *ScalarType) GetOneofVal() isScalarType_OneofVal {
	if x != nil {
		return x.OneofVal
	}
	return nil
}

func (x *ScalarType) GetOneofStringVal() string {
	if x != nil {
		if x, ok := x.OneofVal.(*ScalarType_OneofStringVal); ok {
			return x.OneofStringVal
		}
	}
	return ""
}

func (x *ScalarType) GetOneofInt64Val() int64 {
	if x != nil {
		if x, ok := x.OneofVal.(*ScalarType_OneofInt64Val); ok {
			return x.OneofInt64Val
		}
	}
	return 0
}

func (x *ScalarType) GetOneofBoolVal() bool {
	if x != nil {
		if x, ok := x.OneofVal.(*ScalarType_OneofBoolVal); ok {
			return x.OneofBoolVal
		}
	}
	return false
}

func (x *ScalarType) GetXString() string {
	if x != nil {
		return x.XString
	}
	return ""
}

type isScalarType_OneofVal interface {
	isScalarType_OneofVal()
}

type ScalarType_OneofStringVal struct {
	OneofStringVal string `protobuf:"bytes,18,opt,name=oneof_string_val,json=oneofStringVal,proto3,oneof"`
}

type ScalarType_OneofInt64Val struct {
	OneofInt64Val int64 `protobuf:"varint,19,opt,name=oneof_int64_val,json=oneofInt64Val,proto3,oneof"`
}

type ScalarType_OneofBoolVal struct {
	OneofBoolVal bool `protobuf:"varint,20,opt,name=oneof_bool_val,json=oneofBoolVal,proto3,oneof"`
}

func (*ScalarType_OneofStringVal) isScalarType_OneofVal() {}

func (*ScalarType_OneofInt64Val) isScalarType_OneofVal() {}

func (*ScalarType_OneofBoolVal) isScalarType_OneofVal() {}

var File_test_scalar_type_proto protoreflect.FileDescriptor

const file_test_scalar_type_proto_rawDesc = "" +
	"\n" +
	"\x16test/scalar_type.proto\x12\x06simple\"\x85\x06\n" +
	"\n" +
	"ScalarType\x12\"\n" +
	"\n" +
	"secret_val\x18\x01 \x01(\tB\x03\x80\x01\x01R\tsecretVal\x12\x1d\n" +
	"\n" +
	"double_val\x18\x02 \x01(\x01R\tdoubleVal\x12\x1b\n" +
	"\tfloat_val\x18\x03 \x01(\x02R\bfloatVal\x12\x1b\n" +
	"\tint32_val\x18\x04 \x01(\x05R\bint32Val\x12\x1b\n" +
	"\tint64_val\x18\x05 \x01(\x03R\bint64Val\x12\x1d\n" +
	"\n" +
	"uint32_val\x18\x06 \x01(\rR\tuint32Val\x12\x1d\n" +
	"\n" +
	"uint64_val\x18\a \x01(\x04R\tuint64Val\x12\x1d\n" +
	"\n" +
	"sint32_val\x18\b \x01(\x11R\tsint32Val\x12\x1d\n" +
	"\n" +
	"sint64_val\x18\t \x01(\x12R\tsint64Val\x12\x1f\n" +
	"\vfixed32_val\x18\n" +
	" \x01(\aR\n" +
	"fixed32Val\x12\x1f\n" +
	"\vfixed64_val\x18\v \x01(\x06R\n" +
	"fixed64Val\x12!\n" +
	"\fsfixed32_val\x18\f \x01(\x0fR\vsfixed32Val\x12!\n" +
	"\fsfixed64_val\x18\r \x01(\x10R\vsfixed64Val\x12\x19\n" +
	"\bbool_val\x18\x0e \x01(\bR\aboolVal\x12\x1d\n" +
	"\n" +
	"string_val\x18\x0f \x01(\tR\tstringVal\x12\x1b\n" +
	"\tbytes_val\x18\x10 \x01(\fR\bbytesVal\x122\n" +
	"\benum_val\x18\x11 \x01(\x0e2\x17.simple.ScalarType.EnumR\aenumVal\x12*\n" +
	"\x10oneof_string_val\x18\x12 \x01(\tH\x00R\x0eoneofStringVal\x12(\n" +
	"\x0foneof_int64_val\x18\x13 \x01(\x03H\x00R\roneofInt64Val\x12&\n" +
	"\x0eoneof_bool_val\x18\x14 \x01(\bH\x00R\foneofBoolVal\x12\x17\n" +
	"\a_String\x18\x15 \x01(\tR\x06String\"*\n" +
	"\x04Enum\x12\n" +
	"\n" +
	"\x06ENUM_0\x10\x00\x12\n" +
	"\n" +
	"\x06ENUM_1\x10\x01\x12\n" +
	"\n" +
	"\x06ENUM_2\x10\x02B\v\n" +
	"\toneof_valB2Z0github.com/kei2100/protoc-gen-go-log-valuer/testb\x06proto3"

var (
	file_test_scalar_type_proto_rawDescOnce sync.Once
	file_test_scalar_type_proto_rawDescData []byte
)

func file_test_scalar_type_proto_rawDescGZIP() []byte {
	file_test_scalar_type_proto_rawDescOnce.Do(func() {
		file_test_scalar_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_scalar_type_proto_rawDesc), len(file_test_scalar_type_proto_rawDesc)))
	})
	return file_test_scalar_type_proto_rawDescData
}

var file_test_scalar_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_scalar_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_scalar_type_proto_goTypes = []any{
	(ScalarType_Enum)(0), // 0: simple.ScalarType.Enum
	(*ScalarType)(nil),   // 1: simple.ScalarType
}
var file_test_scalar_type_proto_depIdxs = []int32{
	0, // 0: simple.ScalarType.enum_val:type_name -> simple.ScalarType.Enum
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_test_scalar_type_proto_init() }
func file_test_scalar_type_proto_init() {
	if File_test_scalar_type_proto != nil {
		return
	}
	file_test_scalar_type_proto_msgTypes[0].OneofWrappers = []any{
		(*ScalarType_OneofStringVal)(nil),
		(*ScalarType_OneofInt64Val)(nil),
		(*ScalarType_OneofBoolVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_scalar_type_proto_rawDesc), len(file_test_scalar_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_scalar_type_proto_goTypes,
		DependencyIndexes: file_test_scalar_type_proto_depIdxs,
		EnumInfos:         file_test_scalar_type_proto_enumTypes,
		MessageInfos:      file_test_scalar_type_proto_msgTypes,
	}.Build()
	File_test_scalar_type_proto = out.File
	file_test_scalar_type_proto_goTypes = nil
	file_test_scalar_type_proto_depIdxs = nil
}
