name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.0-rc.2'
      - uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: go version
      - run: go env
      - run: protoc --version
      - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - run: make test
